### PR TITLE
Add c sharp support

### PR DESCRIPTION
**Pull request by gokul-the-dev**
Hello! 👋

This PR adds support for [C# Programming Language](https://learn.microsoft.com/en-us/dotnet/csharp/).

### CODE REVIEW

**Comment by DamianRivas** [comment]
Thanks for doing this @gokul-the-dev! There was a recent change with the structure of the code and now the boilerplates go in their own folder. Would you be able to take a look and see if you can implement changes to resolve conflicts?

**Comment by DamianRivas** [comment]
I'll hold off on releasing v0.11.0 for a bit to see if we can get this in prior to that 🙂

**Comment by gokul-the-dev** [comment]
@DamianRivas I have made changes based on the modified structure. Please take a review when you get time

**Comment by DamianRivas** [comment]
Thank you 🎉

**Pull request merged**
